version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: engagemate-db
    environment:
      POSTGRES_DB: engagemate
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
