version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: engagemate-db
    environment:
      POSTGRES_DB: engagemate
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: engagemate-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://dev:dev@postgres:5432/engagemate
      - NODE_ENV=production
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
